### ISSUE TITLE
大佬，运行了你的豆瓣程序，会报以下错误，

### ISSUE THREAD

**Issue by fuxinran** [SergioJune/Spider-Crack-JS#21]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python36\lib\subprocess.py", line 1063, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 41: illegal multibyte sequence

Traceback (most recent call last):
  File "E:/douban/douban.py", line 14, in <module>
    print((ctx.call('decrypt','r')))
  File "C:\Users\Administrator\.virtualenvs\douban\lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "C:\Users\Administrator\.virtualenvs\douban\lib\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "C:\Users\Administrator\.virtualenvs\douban\lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "C:\Users\Administrator\.virtualenvs\douban\lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "C:\Users\Administrator\.virtualenvs\douban\lib\site-packages\execjs\_external_runtime.py", line 87, in _exec_
    output = self._exec_with_pipe(source)
  File "C:\Users\Administrator\.virtualenvs\douban\lib\site-packages\execjs\_external_runtime.py", line 103, in _exec_with_pipe
    stdoutdata, stderrdata = p.communicate(input=input)
  File "C:\Python36\lib\subprocess.py", line 843, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\Python36\lib\subprocess.py", line 1113, in _communicate
    stdout = stdout[0]
IndexError: list index out of range

**Comment by SergioJune** [comment]
这个是execjs的问题，麻烦看清楚点文章再来
