### ISSUE TITLE
编码报错

### ISSUE THREAD

**Issue by wangbinfei** [SergioJune/Spider-Crack-JS#6]
我在window下运行pingduoduo的,已经装有node.js了.然后一运行就报错
UnicodeEncodeError: 'gbk' codec can't encode character '\xcc' in position 59196: illegal multibyte sequence
具体
Traceback (most recent call last):
  File "pinduoduo.py", line 2239, in <module>
    anti_content = ctx.call('get_anti', url)
  File "F:\anaconda\lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "F:\anaconda\lib\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "F:\anaconda\lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "F:\anaconda\lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "F:\anaconda\lib\site-packages\execjs\_external_runtime.py", line 87, in _exec_
    output = self._exec_with_pipe(source)
  File "F:\anaconda\lib\site-packages\execjs\_external_runtime.py", line 103, in _exec_with_pipe
    stdoutdata, stderrdata = p.communicate(input=input)
  File "F:\anaconda\lib\subprocess.py", line 933, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "F:\anaconda\lib\subprocess.py", line 1255, in _communicate
    self._stdin_write(input)
  File "F:\anaconda\lib\subprocess.py", line 867, in _stdin_write
    self.stdin.write(input)
UnicodeEncodeError: 'gbk' codec can't encode character '\xcc' in position 59196: illegal multibyte sequence
这是js有问题呢?还是execjs需要设置编码吗?

**Comment by wangbinfei** [comment]
祈祷大佬降临中....

**Comment by SergioJune** [comment]
这个问题在我的一篇文章里面提过了，https://sergiojune.com/2019/03/12/python%E8%BF%90%E8%A1%8Cexecjs%E4%B8%AD%E5%87%BA%E7%8E%B0%E7%BC%96%E7%A0%81%E9%97%AE%E9%A2%98/
这里有写，不过到时在安装库的时候需要改回来，要不会安装失败
