### ISSUE TITLE
调用js后，提示缺少标示符、字符串或数字

### ISSUE THREAD

**Issue by Voccoo** [SergioJune/Spider-Crack-JS#7]
Traceback (most recent call last):
  File "E:/Data_backup/Pdd/pdd_2.py", line 70, in <module>
    run()
  File "E:/Data_backup/Pdd/pdd_2.py", line 47, in run
    anti_content = ctx.call('get_anti', url)
  File "D:\Anaconda\lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "D:\Anaconda\lib\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "D:\Anaconda\lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "D:\Anaconda\lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "D:\Anaconda\lib\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "D:\Anaconda\lib\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: SyntaxError: 缺少标识符、字符串或数字

**Comment by Voccoo** [comment]
大佬有什么好的解决办法没。找了一圈没找到合适的解决方式

**Comment by SergioJune** [comment]
你这个问题我解决不了，找不出哪里错误，你可以先在webstrom上运行js代码看看能不能正常获取，如果出错的话你也可以看到错误的地方

**Comment by airwolf2026** [comment]
> 大佬有什么好的解决办法没。找了一圈没找到合适的解决方式

是不是vs里面跑的python?

**Comment by Jeremy-ttt** [comment]
安装nodejs，然后在pycharm或者vs里设置环境
